language: python
# command to install dependencies
install: "make"
# command to run tests
script:
  - make test-readme
  - make ci
cache: pip
jobs:
  include:
    - stage: test
      python: '3.8'
    - stage: coverage
      python: '3.8'
      script: codecov
