name: test

on:
  - push
  - pull_request

permissions:
  contents: read

concurrency:
  group: test-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pyenv
        run: |
          curl https://pyenv.run | bash

      - name: Install dependencies
        run: |
          make init

      - name: Run tests
        run: |
          make ci
